n=input('digite algo: ')
print ('o tipo primitivo desse valor e ', type(n))
print ('so tem espaco?? ',n.isspace())
print ('e um numero? ',n.isnumeric())
print ('e alfabetico? ',n.isalpha())
print ('e alfanumerico? ',n.isalnum())
print('esta em maiuscula? ',n.isupper())
print('esta em minuscula? ', n.islower())
print('esta capitalizda? ', n.istitle())
